### ISSUE TITLE
webdriver-manager stop command

### ISSUE THREAD

**Issue by demonfiddler** [angular/webdriver-manager#157] opened 2016-11-21 16:10 UTC
Just as there is a webdriver-manager start command to start the Selenium server, we need a matching webdriver-manager stop command as a programmatic means to shut down the Selenium server.

I have been unable to understand how webdriver-manager start launches the Selenium server, and have been unable to determine which process is actually running the server, and consequently once it's been launched by Karma I've found no means to shut it down again manually - I can't even find a process to kill. 

The reason for the programmatic shutdown requirement is that my Protractor tests need to run against a later version of selenium-standalone-server (3.0.1) configured with bang-up-to-date WebDriver versions - the Selenium (2.47.1) and WebDriver versions installed by even the latest webdriver-manager (10.2.4) seem to be well out of date.

**Comment by cnishina** [comment] 2016-11-22 21:33
This appears to be resolved with https://github.com/angular/webdriver-manager/commit/338fffddf68ac2767aa5c226ba5374451b9e5308.

**Closed by cnishina** 2016-11-22 21:33 UTC

**Comment by lufecir** [comment] 2017-09-01 09:12
I'm sorry, but it does not seem to me that the referenced commit solves the issue of actually stopping the webdriver. 
The shutdown command is indeed available in webdriver-manager, but the [documentation](https://www.npmjs.com/package/webdriver-manager) clearly states that shutting down standalone server 3.x.x is not yet supported.

Which seems to be confirmed by a test I did:

`> webdriver-manager shutdown
[10:11:18] I/shutdown - Attempting to shut down selenium nicely`

The message says 'Attempting to shutdown' but nothing happens.

I would really like to know how I can shutdown standalone server 3.x. There seems to be some discussion around this, and [this comment](https://github.com/SeleniumHQ/selenium/issues/2852#issuecomment-268324091) suggests that by starting the selenium server differently would allow to execute an execute command like we used to have.

So I am wondering: is there a way to start webdriver in such a way that it can be properly shutdown from a script?
We had our Protractor tests running nicely on the CI server with an older version of Protractor and webdriver-manager, but after upgrading to Protractor 5.x, the shutdown is no longer working and blocks the next run of our Protractor tests.

**Comment by cnishina** [comment] 2017-09-01 17:38
So the commit that was provided did solve this particular problem. There is an outstanding issue on this...I believe you are looking for https://github.com/angular/webdriver-manager/issues/199. You can voice your issues there to keep the conversation in one place rather than closed issues.
