### ISSUE TITLE
webdriver-manager downloads chromedriver_mac64_m1.zip on intel mac

### ISSUE THREAD

**Issue by furnace915** [angular/webdriver-manager#477] opened 2021-01-07 01:35 UTC
My Protractor scripts started throwing the following error on startup.  This just started happening today without any changes happening on my end:
 ([20:24:00] I/direct - Using ChromeDriver directly...
[20:24:01] E/launcher - spawn Unknown system error -86)

I reviewed the webdriver-manager output and it looks like the wrong driver is being downloaded for my MacOs Catalina (2017 Intel):
[20:21:46] I/downloader - curl -o/Users/xxx/Projects/my-project/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_87.0.4280.88.zip https://chromedriver.storage.googleapis.com/87.0.4280.88/chromedriver_mac64_m1.zip

**Comment by pawelusfr** [comment] 2021-01-07 10:32
Duplicate of https://github.com/angular/webdriver-manager/issues/476

**Comment by cnishina** [comment] 2021-01-09 00:54
Yup. This is important enough to publish a fix. We'll get something out this weekend.

**Comment by cnishina** [comment] 2021-01-09 19:39
This has been published 12.1.8. After updating to version 12.1.8, you will need to run `webdriver-manager clean` before running `webdriver-manager update`

**Comment by cnishina** [comment] 2021-01-09 19:41
Closing as duplicate.

**Closed by cnishina** 2021-01-09 19:41 UTC
