### ISSUE TITLE
pree2e always remove the geckodriver

### ISSUE THREAD

**Issue by lygstate** [angular/webdriver-manager#176] opened 2016-12-11 14:53 UTC
https://github.com/mozilla/geckodriver/releases/download/v0.9.0/geckodriver-v0.9.0-win64.zip

**Comment by lygstate** [comment] 2016-12-11 15:18
I hope webdriver-manager update only need to be executed only a single time.

**Comment by cnishina** [comment] 2016-12-12 19:20
I'm not sure what this actually applies to, what new feature you want, or what the issue is. Please provide more detailed information.

**Comment by lygstate** [comment] 2016-12-13 08:58
npm run pree2e always redownload gecko driver

**Comment by cnishina** [comment] 2016-12-13 18:57
So your question is to not download gecko driver every time? What version of webdriver-manager are you using? Are you on the latest? Which project has this `npm run pree2e`? What is the `pree2e` command actually do? Are you using angular-cli? Like I suggested above, more information is needed. Please provide as much detail as possible.

**Comment by lygstate** [comment] 2016-12-13 23:59
yes newest angular-cli  version generated ng2 project

**Comment by cnishina** [comment] 2016-12-14 00:04
Closing this issue since angular-cli has been addressed. See https://github.com/angular/angular-cli/pull/3244.

If you want these changes in your project, change `npm run pree2e` in your `package.json` to:

```
"pree2e": "webdriver-manager update --standalone false --gecko false"
```

The project angular-cli creates for Protractor uses direct connect for Protractor so the selenium standalone binary is also not needed.

**Closed by cnishina** 2016-12-14 00:04 UTC
Labels: status: needs more info
