### ISSUE TITLE
webdriver-manager update downloads an incompatible version of chromedriver

### ISSUE THREAD

**Issue by arobinson** [angular/webdriver-manager#376] opened 2019-04-29 17:21 UTC
Now that Chrome 74 is the stable version, our unit tests are no longer working. Looking into the issue, we see that Chrome 74 is out, but `webdriver-manager update` is downloading 2.46 instead of the correct version of `74.0.3729.6`.

Even if we run the command with the correct version, it is failing:
```
webdriver-manager update --versions.chrome=74.0.3729.6
webdriver-manager: using project version 12.1.2
[11:16:39] E/downloader - undefined
[11:16:39] I/update - chromedriver: file exists /Users/andrew/development/work/client/dev/client-source/node_modules/webdriver-manager/selenium/chromedriver_74.0.3729.6.zip
[11:16:39] I/update - chromedriver: unzipping chromedriver_74.0.3729.6.zip
(node:57948) UnhandledPromiseRejectionWarning: Invalid filename
(node:57948) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

Opening the `node_modules/webdriver-manager/selenium/update-config.json` I can see that it is saying 2.46 is the latest instead of 74.0.3729.6

From http://chromedriver.chromium.org/:
> Latest stable release: ChromeDriver 74.0.3729.6

This is blocking our ability to test our code. I'd appreciate any work-around if any is known in getting Chrome 74 working with `webdriver-manager`

**Comment by macroking** [comment] 2019-04-29 19:31
Update protractor/webdriver-manager to the latest version.

**Comment by cnishina** [comment] 2019-04-29 20:12
I'll have a hot fix out in the next few days for this. Latest webdriver-manager does work BUT:

* It is not the version Protractor 5.4.2 uses. Installing the latest does not work with driverProviders/direct or dirverProviders/local. 
* We have a fix for backward compatibility for webdriver-manager 13 but that would also require releasing a new version of Protractor

**Comment by cnishina** [comment] 2019-04-29 20:42
Here is the proposed fix: https://github.com/angular/webdriver-manager/pull/377

Neat that my few days estimate is actually 30 minutes.

**Comment by cnishina** [comment] 2019-04-29 21:24
With the release of Chrome 74 and webdriver-manager 12.1.2 not supporting this is now an official bug.

**Comment by cnishina** [comment] 2019-04-29 21:25
And 12.1.3 has been released! This should resolve the ChromeDriver issue.

How to get it?

- do a fresh install of your node modules directory (remove node_modules folder and do a `npm install`)
- do a forced install `npm install -f`

**Comment by cnishina** [comment] 2019-04-29 21:42
More info on the StackOverflow post: https://stackoverflow.com/questions/55910242/when-using-protractor-5-4-2-webdriver-manager-downloads-2-46-which-is-not-compa/55911176#55911176

**Comment by vsravuri** [comment] 2019-04-29 21:46
@cnishina Thanks for resolving this issue. Verified 12.1.3 is downloading Chrome 74 with proper Selenium Jar file.

**Comment by arobinson** [comment] 2019-04-29 22:21
Looks to be working only if the default version is used. We always specify the version as our jenkins machines have a fixed chrome version and therefore we want to specify the webdriver version. This used to work, but now it is reporting errors in the console.

Command that is failing:
```
webdriver-manager update --versions.chrome=74.0.3729.6
```
Output
```
webdriver-manager: using local installed version 12.1.3
[16:15:48] I/config_source - curl -o/Users/andrew/development/work/client/dev/client-source/node_modules/webdriver-manager/selenium/standalone-response.xml https://selenium-release.storage.googleapis.com/
[16:15:48] I/config_source - curl -o/Users/andrew/development/work/client/dev/client-source/node_modules/webdriver-manager/selenium/chrome-response.xml https://chromedriver.storage.googleapis.com/
[16:15:48] I/config_source - curl -o/Users/andrew/development/work/client/dev/client-source/node_modules/webdriver-manager/selenium/gecko-response.json https://api.github.com/repos/mozilla/geckodriver/releases
[16:15:49] E/downloader - undefined
[16:15:49] I/update - chromedriver: file exists /Users/andrew/development/work/client/dev/client-source/node_modules/webdriver-manager/selenium/chromedriver_74.0.3729.6.zip
[16:15:49] I/update - chromedriver: unzipping chromedriver_74.0.3729.6.zip
(node:78021) UnhandledPromiseRejectionWarning: Invalid filename
(node:78021) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:78021) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[16:15:49] I/downloader - curl -o/Users/andrew/development/work/client/dev/client-source/node_modules/webdriver-manager/selenium/selenium-server-standalone-3.141.59.jar https://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59.jar
[16:15:49] I/downloader - curl -o/Users/andrew/development/work/client/dev/client-source/node_modules/webdriver-manager/selenium/geckodriver-v0.24.0.tar.gz https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-macos.tar.gz
[16:15:51] I/update - geckodriver: unzipping geckodriver-v0.24.0.tar.gz
[16:15:51] I/update - geckodriver: setting permissions to 0755 for /Users/andrew/development/work/client/dev/client-source/node_modules/webdriver-manager/selenium/geckodriver-v0.24.0
```
Using this command does not report the errors:
```
webdriver-manager update
```

**Comment by cnishina** [comment] 2019-04-30 00:22
Yup I can duplicate this on my machine.... :disappointed:

**Comment by scooper91** [comment] 2019-04-30 16:35
@cnishina Is there a workaround for this?

We're installing `stable` `google-chrome` from https://dl.google.com/linux/chrome/deb.

```sh
> google-chrome --version
Google Chrome 74.0.3729.108

> ./node_modules/.bin/webdriver-manager update --versions.chrome=$(google-chrome --version | cut -d ' ' -f 3)
[16:32:13] E/downloader - undefined
[16:32:13] I/update - chromedriver: file exists /tests/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_74.0.3729.108.zip
[16:32:13] I/update - chromedriver: unzipping chromedriver_74.0.3729.108.zip
(node:99) UnhandledPromiseRejectionWarning: Invalid filename
(node:99) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

**Comment by xiaofuh** [comment] 2019-04-30 18:38
Having the exact same issue. as scooper91. 
Is there any workaround to install chrome driver 74.X.xxxxx without using webdriver-manager?

**Comment by cnishina** [comment] 2019-04-30 18:43
Proposed fixes for downloading specific versions, starting specific versions, status, and preventing 75 from being downloaded.

https://github.com/angular/webdriver-manager/issues/376

**Comment by arawinters** [comment] 2019-04-30 18:49
yup. exact same issue here. latest installs 75, chrome version is 74, trying to do a `webdriver-manager update --versions.chrome 74.0.3729.6` results in the issue described above.

**Comment by cnishina** [comment] 2019-04-30 19:38
I just released 12.1.4. This should fix the issues we are seeing with chromedriver 75 and chrome 74 mismatches. Also you should be able to download `--versions.chrome 74.0.3729.6` with 12.1.4. This was broken in 12.1.3.

@arawinters @xiaofuh @scooper91 @vsravuri @arobinson @macroking

**Comment by xiaofuh** [comment] 2019-04-30 20:11
It worked for me. Thanks

**Comment by vsravuri** [comment] 2019-04-30 20:17
@cnishina 

Verified both "webdriver-manager update" & "webdriver-manager update --versions.chrome 74.0.3729.6" with Protractor 5.4.2, ChromeDriver "chromedriver_74.0.3729.6.zip" is downloaded correctly.

**Comment by macroking** [comment] 2019-04-30 20:24
@cnishina  I'll spend some time to add tests around this functionality to prevent incidents like this form happening in future.

**Comment by cnishina** [comment] 2019-04-30 20:27
@macroking This is the legacy branch that I want to be off of. Problem here is that I already wrote these fixes for the master branch and the reason for the new master branch was to have more testing.

**Comment by cnishina** [comment] 2019-04-30 23:00
Here is the StackOverflow post that goes along with this: https://stackoverflow.com/questions/55910242/when-using-protractor-5-4-2-webdriver-manager-downloads-2-46-which-is-not-compa

**Comment by jthimmavajjhala** [comment] 2019-05-07 03:05
@cnishina  : Hello, i tried the step you have mentioned and i also see that the chrome version is pointing out to 74xx but when i run this in the docker , i am running into the same issue : 
[03:01:38] I/config_source - curl -o/app/angular/node_modules/webdriver-manager/selenium/chrome-response.xml https://chromedriver.storage.googleapis.com/
ℹ ｢wdm｣: Compiled successfully.
[03:01:40] I/downloader - curl -o/app/angular/node_modules/webdriver-manager/selenium/chromedriver_74.0.3729.6.zip https://chromedriver.storage.googleapis.com/74.0.3729.6/chromedriver_linux64.zip
[03:01:44] I/update - chromedriver: unzipping chromedriver_74.0.3729.6.zip
[03:01:45] I/update - chromedriver: setting permissions to 0755 for /app/angular/node_modules/webdriver-manager/selenium/chromedriver_74.0.3729.6
[03:01:45] I/launcher - Running 1 instances of WebDriver
[03:01:45] I/direct - Using ChromeDriver directly...
[03:01:46] E/launcher - session not created: This version of ChromeDriver only supports Chrome version 74
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Linux 4.9.60-linuxkit-aufs x86_64)
[03:01:46] E/launcher - SessionNotCreatedError: session not created: This version of ChromeDriver only supports Chrome version 74
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Linux 4.9.60-linuxkit-aufs x86_64)
    at Object.checkLegacyResponse (/app/angular/node_modules/selenium-webdriver/lib/error.js:546:15)
    at parseHttpResponse (/app/angular/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/app/angular/node_modules/selenium-webdriver/lib/http.js:441:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
From: Task: WebDriver.createSession()
    at Function.createSession (/app/angular/node_modules/selenium-webdriver/lib/webdriver.js:769:24)
    at Function.createSession (/app/angular/node_modules/selenium-webdriver/chrome.js:761:15)
    at Direct.getNewDriver (/app/angular/node_modules/protractor/built/driverProviders/direct.js:77:33)
    at Runner.createBrowser (/app/angular/node_modules/protractor/built/runner.js:195:43)
    at q.then.then (/app/angular/node_modules/protractor/built/runner.js:339:29)
    at _fulfilled (/app/angular/node_modules/q/q.js:834:54)
    at /app/angular/node_modules/q/q.js:863:30
    at Promise.promise.promiseDispatch (/app/angular/node_modules/q/q.js:796:13)
    at /app/angular/node_modules/q/q.js:556:49
    at runSingle (/app/angular/node_modules/q/q.js:137:13)
[03:01:46] E/launcher - Process exited with error code 199
An unexpected error occurred: undefined

**Comment by cnishina** [comment] 2019-05-08 04:47
Wow that's weird. So you have Chrome 74 and Chromedriver 74. Okay.... what version of Chrome are you using in this docker file? In my circleci config, I check the chrome version to make sure I know what I'm dealing with. https://github.com/angular/protractor/blob/master/.circleci/config.yml#L13

**Comment by cnishina** [comment] 2019-05-10 21:16
@jthimmavajjhala I created an example test https://github.com/cnishina/protractor542-chrome74 with my output from my desktop. This is using direct connect and I was able to create a session. Is this docker file available to review?

**Comment by cnishina** [comment] 2019-06-04 23:02
Closing this issue.

**Closed by cnishina** 2019-06-04 23:02 UTC
Labels: status: resolved!, type: bug

**Comment by VladimirSolovyev** [comment] 2019-10-23 14:07
I have problem with Chrome driver 75 again:
```
angakok@Z270:~/data/COSdev-job-files/GitProjects/miner.front$ google-chrome --version
Google Chrome 77.0.3865.120 
angakok@Z270:~/data/COSdev-job-files/GitProjects/miner.front$ webdriver-manager version
[17:05:51] I/version - webdriver-manager 12.1.5
angakok@Z270:~/data/COSdev-job-files/GitProjects/miner.front$ webdriver-manager update --standalone=false --gecko=false
[17:06:00] I/config_source - curl -o/home/angakok/data/COSdev-job-files/GitProjects/miner.front/node_modules/protractor/node_modules/webdriver-manager/selenium/chrome-response.xml https://chromedriver.storage.googleapis.com/
[17:06:01] I/downloader - curl -o/home/angakok/data/COSdev-job-files/GitProjects/miner.front/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_75.0.3770.140.zip https://chromedriver.storage.googleapis.com/75.0.3770.90/chromedriver_linux64.zip
[17:06:01] I/update - chromedriver: unzipping chromedriver_75.0.3770.140.zip
[17:06:02] I/update - chromedriver: setting permissions to 0755 for /home/angakok/data/COSdev-job-files/GitProjects/miner.front/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_75.0.3770.140
angakok@Z270:~/data/COSdev-job-files/GitProjects/miner.front$ webdriver-manager update --versions.chrome=77.0.3865.40 --standalone=false --gecko=false
[17:06:11] I/downloader - curl -o/home/angakok/data/COSdev-job-files/GitProjects/miner.front/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_77.0.3865.40.zip https://chromedriver.storage.googleapis.com/77.0.3865.40/chromedriver_linux64.zip
[17:06:11] I/update - chromedriver: unzipping chromedriver_77.0.3865.40.zip
[17:06:12] I/update - chromedriver: setting permissions to 0755 for /home/angakok/data/COSdev-job-files/GitProjects/miner.front/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_77.0.3865.40
angakok@Z270:~/data/COSdev-job-files/GitProjects/miner.front$ webdriver-manager update --versions.chrome=77.0.3865 --standalone=false --gecko=false
[17:06:20] E/downloader - undefined
[17:06:20] I/update - chromedriver: file exists /home/angakok/data/COSdev-job-files/GitProjects/miner.front/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_77.0.3865.zip
[17:06:20] I/update - chromedriver: unzipping chromedriver_77.0.3865.zip
(node:4229) UnhandledPromiseRejectionWarning: Invalid filename
(node:4229) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:4229) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by sheucm** [comment] 2019-11-13 07:10
This solution works for me.
1. `npm i webdriver-manager@latest`
2. `npm i chromedriver --chromedriver_version=LATEST`
3. [Reinstall protractor.](https://stackoverflow.com/questions/55201226/session-not-created-this-version-of-chromedriver-only-supports-chrome-version-7/58105741#58105741) `npm uninstall protractor & npm install --save-dev protractor`

**Comment by MaxMex007** [comment] 2019-12-19 20:40
This issue is back :( now it's happening with Chrome 79.0.3945, on AzureDevops it downloads 79.0.3945.36 but azure only supports 79.0.3945.16 and there's NO way to force webdriver to use this exact version. it automatically downloads the LATEST on 79.0.3945.XXX and this is breaking my deployment.

**Comment by inampude** [comment] 2020-04-24 06:22
installing all the packages globally including chromdriver and making changes to the config.json file of webdriver worked for me :)

**Comment by Suruchi-Garg** [comment] 2020-05-26 14:51
4.0.0 not supporting chrome 83. By launching through URL, getting "data:," in url.

**Comment by sergiybuch** [comment] 2020-07-24 03:11
For me LATEST downloaded chromedriver 85 and Official release of Chrome is 84..

**Comment by defremovSFX** [comment] 2020-07-24 07:28
For us, stable chrome is still 84, but webriver manager downloads chromedriver 85 ...

**Comment by jgomesmv** [comment] 2020-07-24 08:31
We are also facing the same issue. Chrome is on version 84 (stable version) but protractor uses chromedriver 85 (latest version)

**Comment by Thaval** [comment] 2020-07-24 08:41
Same here. How can webdriver use a chrome version that is not even published?
Chrome tells me everything is up to date.

**Comment by Suruchi-Garg** [comment] 2020-07-24 09:35
Relaunch your chrome browser. It worked for me

**Comment by MayurSinghTaunk** [comment] 2020-07-24 10:15
> Same here. How can webdriver use a chrome version that is not even published?
> Chrome tells me everything is up to date.
> 
> Edit: It worked yesterday. Started up the computer this morning and wanted to run the tests again, then the announced problem occured.
> 
> Edit2:
> In case someone is having trouble with ng e2e, protractor and webdriver (chrome). For Angular 9, the following solved the problem for me:
> Download the webdriver of chrome from
> [https://chromedriver.chromium.org/downloads](url)
> 
> Then copy and paste the downloaded driver to your desired destination (in my case, it's the root of my angular app where protractor.conf.js is, I created a folder called "chromeDrivers" on the root level) and specify the path to the **.exe** in the protractor.conf.js file like this (notice the path is relative):
> 
> exports.config = {
> chromeDriver: './chromeDrivers/chromedriver_win32_84.0.4147.30/chromedriver.exe',
> //rest of config
> }
> 
> Then, back on the cmd, just run `ng e2e --webdriverUpdate=false`. This will prevent protractor from using webdriver-manager in node_modules and it will use your chromeDriver at the specified path **after** building your app. If you receive a _spawn ENOENT_ error, you probably didn't point to the exe but to a folder.
> 
> Hope it helps someone, although it's not directly a webdriver-manager issue.

Thanks!!! this works for me

**Comment by kdp88** [comment] 2020-07-24 13:03
jenkins failing for same reasons as above
`[11:42:40] I/update - chromedriver: file exists /app/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_85.0.4183.38.zip
[11:42:40] I/update - chromedriver: unzipping chromedriver_85.0.4183.38.zip
[11:42:45] I/update - chromedriver: setting permissions to 0755 for /app/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_85.0.4183.38
[11:42:45] I/update - chromedriver: chromedriver_85.0.4183.38 up to date
Report destination:   reports/screenshots/report.html
[11:42:45] I/launcher - Running 1 instances of WebDriver
[11:42:45] I/direct - Using ChromeDriver directly...
[11:42:47] E/launcher - session not created: This version of ChromeDriver only supports Chrome version 85`

docker file:
`RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
RUN apt-get update && apt-get install -y google-chrome-stable`

docker output: 
`Get:1 http://dl.google.com/linux/chrome/deb stable/main amd64 google-chrome-stable amd64 84.0.4147.89-1 [69.6 MB]`

what steps should i take

**Comment by TylerNielsen** [comment] 2020-07-24 14:15
The following worked for us:

1. We have webdriver-manager installed as project dependency. 

2. we call `webdriver-manager update --versions.chrome 84.0.4147.30` prior to running our tests This will install the 84 chromedriver version in ./node_modules/webdriver-manager/selenium/.

3. We then update the protractor.conf file to have this line in the root of exports.config: `chromeDriver:"./node_modules/webdriver-manager/selenium/chromedriver_84.0.4147.30.exe"`

Protractor still installs chromedriverr 85, but it will use the 84 version.

**Comment by TylerNielsen** [comment] 2020-07-24 14:22
Should this be a new issue thread since this one has already been caused? We don't know if it has the same root cause as the past similar issues.

**Comment by Box-shadow-finished8** [comment] 2025-02-04 15:47
@vsravuri https://stackdev.space/questions/developing-and-utilizing-a-repository-for-diverse-resources-aside-from-text
