### ISSUE TITLE
webdriver-manager start throwing error Exception in thread "main" java.lang.NoSuchMethodError:

### ISSUE THREAD

**Issue by WaqasRaja777** [angular/webdriver-manager#291] opened 2017-12-06 23:58 UTC
I'm facing issues while trying to start webdriver-manager.

This is the error I'm getting.

09:28:36.516 INFO - Driver class not found: org.openqa.selenium.phantomjs.PhantomJSDriver
Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.collect.ImmutableList.toIm
mutableList()Ljava/util/stream/Collector;
        at org.openqa.selenium.remote.server.DefaultDriverFactory.<clinit>(DefaultDriverFactory.java
:56)
        at org.openqa.selenium.remote.server.SeleniumServer.boot(SeleniumServer.java:145)
        at org.openqa.grid.selenium.GridLauncherV3$1.launch(GridLauncherV3.java:237)
        at org.openqa.grid.selenium.GridLauncherV3.main(GridLauncherV3.java:82)
[09:28:36] I/start - Selenium Standalone has exited with code 1

Any clues on what could be wrong here?

**Comment by cnishina** [comment] 2019-04-11 11:09
We do not support PhantomJSDriver. That might be the root cause. Closing this since we do not support it.

**Closed by cnishina** 2019-04-11 11:09 UTC
