### ISSUE TITLE
Angular project fails e2e on webdriver-manager step

### ISSUE THREAD

**Issue by jeroenheijmans** [angular/webdriver-manager#329] opened 2018-10-24 06:41 UTC
I've been having [a conversation with AppVeyor](https://help.appveyor.com/discussions/problems/16920-builds-failing-on-chromedriver-download-angular-6-cli-e2e-tests-step) about my builds failing in that CI environment on the webdriver-manager step. They have investigated and concluded it's going to need to be fixed in the `webdriver-manager` repository, and they might well be right.

I'm not sure what the _root cause_ is, but I can reliably reproduce the issue. You can see for yourself by cloning [this repository (just an `ng new app --inline-style` app with `.yml` file)](https://github.com/jeroenhinfi/experiments-appveyor) and configure it in AppVeyor. Or you can check out [my AppVeyor project building it](https://ci.appveyor.com/project/JeroenHeijmans61392/experiments-appveyor). 

What you should see is this kind of error output:

```
[13:43:00] I/file_manager - creating folder C:\projects\projectnamehere\node_modules\protractor\node_modules\webdriver-manager\selenium
[13:43:00] I/config_source - curl -oC:\projects\projectnamehere\node_modules\protractor\node_modules\webdriver-manager\selenium\chrome-response.xml https://chromedriver.storage.googleapis.com/
ℹ ｢wdm｣: Compiled successfully.
events.js:183
      throw er; // Unhandled 'error' event
      ^
Error: read ECONNRESET
    at TLSWrap.onread (net.js:622:25)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! projectnamehere@0.0.0 e2e: `node git-version.js && ng e2e`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the projectnamehere@0.0.0 e2e script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\appveyor\AppData\Roaming\npm-cache\_logs\2018-09-18T13_43_01_245Z-debug.log
Command exited with code 1
```

Where previously (on builds that were succeeding) you'd be seeing this:

```
[13:43:21] I/file_manager - creating folder C:\projects\projectnamehere\node_modules\protractor\node_modules\webdriver-manager\selenium
[13:43:21] I/config_source - curl -oC:\projects\projectnamehere\node_modules\protractor\node_modules\webdriver-manager\selenium\chrome-response.xml https://chromedriver.storage.googleapis.com/
ℹ ｢wdm｣: Compiled successfully.
[13:43:22] I/downloader - curl -oC:\projects\projectnamehere\node_modules\protractor\node_modules\webdriver-manager\selenium/chromedriver_2.42.zip https://chromedriver.storage.googleapis.com/2.42/chromedriver_win32.zip
[13:43:22] I/update - chromedriver: unzipping chromedriver_2.42.zip
[13:43:23] I/launcher - Running 1 instances of WebDriver
[13:43:23] I/direct - Using ChromeDriver directly...
Jasmine started

etc.
```

There are some more details [on the AppVeyor forums](https://help.appveyor.com/discussions/problems/16920-builds-failing-on-chromedriver-download-angular-6-cli-e2e-tests-step), but the most important stuff I've repeated above. AppVeyor support most recently concluded this:

> Posted by Owen McDonnell on Oct 24, 2018 @ 01:39 AM (Support Staff)
> I think this is likely some network latency issue since it looks like the webdriver-manager module is downloading an xml then immediately parsing it and making another request for the latest drivers.
>
> As such, it is not really revelatory to try other CI machines and compare results. But if you're interested, I've enabled building from GCE workers so if you want to try some builds on those machines just add appveyor_build_worker_cloud: gce to your environment variables. Be aware that GCE workers take a little longer to provision so your build may take a few minutes to begin.
>
> I think short of making a pull request to said npm module, I would consider the "workaround" as a resolution.

Can anyone more knowledgeable perhaps comment on this issue? I'm happy to help investigate further, but I'm not sure where to start (short of close-reading this entire repo's codebase...).

**Comment by vort3xxx** [comment] 2018-10-24 15:37
What's your current version of nodejs?  If it's 8.12.0, this is a dupe of: https://github.com/angular/webdriver-manager/issues/326

**Comment by jeroenhinfi** [comment] 2018-10-24 16:02
Thx for the response. I can confirm (visible in the AppVeyor logs) that I've got NodeJS 8.12.0. However:

- I don't see any SSL-related errors in my logs
- if I instruct AppVeyor to _retry the exact same operation_ it does consistently succeed on second try

I've only skimmed #326 but at first glance the above points suggest that it might be a different issue? (Might dive deeper into that later if I find time.)

**Comment by markleppke** [comment] 2018-10-24 16:13
Take a deeper look at #326 It asks to change the title of the issue as they identified it was unrelated to SLL from what they could tell. This may be related to this: https://github.com/nodejs/node/issues/23237

**Comment by jeroenheijmans** [comment] 2018-10-25 06:55
@markleppke Yes, you are right. Apologies for not reading deeper into linked issue right away.

My symptoms are very similar, as is my repro, so this issue is most likely a dupe.

**Comment by cnishina** [comment] 2019-04-11 00:09
Closing as duplicate to #326

**Closed by cnishina** 2019-04-11 00:09 UTC
