### ISSUE TITLE
webdriver-manager --update uses unreleased chrome driver versions 03_13_2019

### ISSUE THREAD

**Issue by osenyuk** [angular/webdriver-manager#349] opened 2019-03-14 10:12 UTC
Seems like webdriver from WebdriverManager update only wants to work with Google Chrome version 74 witch is not yet released

[SmokeSuiteGoToTest.runOn] org.openqa.selenium.SessionNotCreatedException: session not created: This version of ChromeDriver only supports Chrome version 74
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Windows NT 10.0.14393 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 3.02 seconds
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'
System info: host: 'TOOLS-AGENT1', ip: '172.21.0.140', os.name: 'Windows Server 2016', os.arch: 'amd64', os.version: '10.0', java.version: '10.0.1'
Driver info: driver.version: ChromeDriver

What to do in this situation?

**Comment by vsravuri** [comment] 2019-03-15 03:28
Running into same issue

**Comment by osenyuk** [comment] 2019-03-15 08:21
> Running into same issue

Seems like their are not in hurry to fix the issues :D

**Comment by vsravuri** [comment] 2019-03-23 17:27
@cnishina 

Protractor 6.00 is released. Noticed **webdriver-manager update** downloads unreleased version of ChromeDriver. Current stable version of Chrome is 73 but webdriver-manager update downloads ChromeDriver 74 (beta version) which is not compatible with Chrome 73.

**Error message: session not created: This version of ChromeDriver only supports Chrome version 74
Error: session not created: This version of ChromeDriver only supports Chrome version 74**

http://chromedriver.chromium.org/downloads

**Comment by cnishina** [comment] 2019-03-24 22:01
So this is as designed. It should download the latest. The assumption is that the latest Chrome works with the latest Chromedriver. Thats not always the case. You can download a specific version of the driver. I am thinking abouta feature to download a chromium version together with it. Closing since this is as designed.

**Closed by cnishina** 2019-03-24 22:01 UTC

**Comment by venukalakota** [comment] 2019-03-25 12:31
I am getting the same error today, it was working fine last friday. Can you guys let me know if you have found a solution for this.

Thanks,
Venu.

**Comment by Buster2694** [comment] 2019-03-25 15:57
I am having the same issue, has anyone been able to work around this yet?

**Comment by emilyYue** [comment] 2019-03-25 19:09
I am having the same issue... any update?

**Comment by tomfaltesek** [comment] 2019-03-25 19:23
As a temporary solution in my CI/CD pipeline, I specifically install 2.46:
`webdriver-manager update --versions.chrome 2.46`

This works for now. Once my organization gets Chrome 74, hopefully I can remove the specific version.

**Comment by venukalakota** [comment] 2019-03-26 10:48
Any updates on the issue please, can anyone let me know what timelines will the protractor guys follow to fix this kind of issues normally!

**Comment by kotprav** [comment] 2019-03-26 16:17
I've just updated protractor to the version 5.4.2 and webdriver-manager to 12.1.1 and everything works fine.

**Comment by rafalf** [comment] 2019-03-29 10:38
This is a little silly. why somebody has made it to download latest chrome if its not yet supported ( browser not released)
the same for protractor, version 6 is release but protractor API is not yet up to date for Selenium 4.
People have things automated and they would expect to work things seamlessly and if it breaks, then they should be able to update their code , not the other way around that we need to downgrade things

**Comment by saturn72** [comment] 2019-05-01 10:16
bumped into the same issue.
Suggest to make it download the latest release by default, and any other version should have explicit `--version.chrome` argument

**Comment by cnishina** [comment] 2019-05-01 20:30
Please try 12.1.4. This has been resolved.
