### ISSUE TITLE
Darwin (Mac64) Chromdriver tries to install Mac32 version

### ISSUE THREAD

**Issue by Wo1v3r** [angular/webdriver-manager#284] opened 2017-11-03 03:17 UTC
Installing on MacBook Pro 64bit, tries to get wrong version @ 

`downloading https://chromedriver.storage.googleapis.com/2.28/chromedriver_mac32.zip...`

**Comment by cnishina** [comment] 2017-11-08 18:14
I believe at one point we were downloading only 32 version. Please update your webdriver-manager to the latest and verify

**Comment by cnishina** [comment] 2017-11-08 18:27
This is not reproducible. How it works now:

Downloads the entire XML response for chromedriver. Get either the `latest` or the user specified version from the `versions.chrome` flag. It then gets your OS version and picks either the 32 or 64 bit versions of the binary. For chromedriver, it prefers the 64 bit version. For something like IEDriver, it downloads the 32 bit version.

**Comment by cnishina** [comment] 2017-11-11 01:12
Since it is not reproducible, closing this issue.

Please use the latest.

**Closed by cnishina** 2017-11-11 01:12 UTC
Labels: status: needs more info
