### ISSUE TITLE
alternate_cdn is saved but never used to generate the binary url (except android_sdk)

### ISSUE THREAD

**Issue by michaelblumenstein** [angular/webdriver-manager#214] opened 2017-02-22 14:08 UTC
For issue https://github.com/angular/webdriver-manager/issues/96 there is already described, that --alternate_cdn is not respected for downloading the binaries.

There was a fix, which saves the cdn url in the abstract class binary (https://github.com/angular/webdriver-manager/commit/b183fadd4ae0b47b0773d6979d090c74419ee327), but the saved cdn is not used to generate the urls where the binaries should be retrieved.

**Comment by michaelblumenstein** [comment] 2017-02-22 14:13
I could provide a fix, but i'm not quite sure which would be the recommended way to use the provided alternate_cdn url.

I see multiple possibilities to apply a fix:

1. Respect alternate_cdn in the configSource objects of the binaries in the implementation of the getUrl method.
2. Overwrite the resolved url host in every call to the method Downloader.getFile();

These are two options i would see as an appropriate solution. There are other options too, to resolve this issue, so i'm asking here, which method would be a good solution according to your coding conventions.

**Comment by cnishina** [comment] 2017-03-03 04:24
Thanks for pointing this out! I probably did not pass down the `altnerative_cdn` variable during the rewrite.

**Comment by michaelblumenstein** [comment] 2017-03-03 06:44
@cnishina: So i assume there was already an implementation for this and you will restoring this part of the implementation? 
Otherwise i could also provide a fix, just have to know what would be the preferred way for the fix.

**Comment by cnishina** [comment] 2017-03-03 18:36
I'll work on the fix for this. I hope to get around to it on Sunday.

**Comment by cnishina** [comment] 2017-03-03 19:47
I have thought about this and I don't think I've ever been a fan of the alternative cdn parameter.

Possible solutions:

1. Remove the alternative cdn flag

2. The user still needs to download the xml and/or json file(s) from the internet. We replace the domain name with the alternative cdn value, then the user can download the file. If the user cannot download the xml or json files, we recommend that they write their own bash script.

I like solution 1 because it is easy. Solution 2 might not work for everyone and is misleading. If they are stuck behind a firewall and cannot proxy, this will not work.

**Comment by cnishina** [comment] 2017-03-06 19:56
Alright, since I haven't heard back, I think I'm going to do solution 1. I have this `alternativeDownloadUrl` variable as an override. This might be a good solution when I get around to implementing it, see https://github.com/angular/webdriver-manager/blob/master/lib/binaries/chrome_driver.ts#L34

**Comment by michaelblumenstein** [comment] 2017-03-16 12:43
Sorry for the late reply, i was on a trip the last few days. 

@cnishina: So you are implementing a solution? Otherwise my offer is valid to implement your suggested solution.

**Comment by zwolej** [comment] 2017-03-16 13:44
Hey, I'm behind proxy and after upgrading to webdriver 12.x alternate_cdn seems to not working. The first solution is about creating new flag  alternativeDownloadUrl instead alternateCdn ?

**Comment by michaelblumenstein** [comment] 2017-03-17 12:37
I have created PR https://github.com/angular/webdriver-manager/pull/226. But i have to sign the CLA, which has to be done from my home network. I will do it in about a day.

**Comment by michelmeeuwissen** [comment] 2017-08-17 10:21
Problem still seems to occur while the PR is closed? Am I missing something.
It does not respect the parameter: `--alternate_cdn` or the older `--alternate_download_url`
Using 12.0.6 atm with the following command:

`webdriver-manager update --standalone=false --gecko=false --versions.chrome=2.31 --ignore_ssl --alternate_download_url=http://mylocahost.com/chromedriver/ --alternate_cdn=http://mylocahost/chromedriver/`

**Comment by hpham** [comment] 2017-09-15 20:55
I think it does not fix the problem, because you have several repositories for selenium , chromedriver etc. because of that you have to serveral cdn or alternate_download_urls for these repository. 

see: https://github.com/angular/webdriver-manager/blob/master/config.json

**Comment by williamscs** [comment] 2018-01-23 14:04
@michelmeeuwissen The problem is that CLA wasn't signed, so PR was not merged. It looks like there are checks for this.alternativeDownloadUrl in the code now for version retrieval, but it doesn't appear to ever be assigned. I'm guessing that in binary.ts we could assign it to the same values as this.cdn, but I don't know if that's desired behavior.

It just depends on if there are people that would like to use an alternative cdn, but still would like to make a retrieval to see versions available. Right now, it's still broken if you are working on an internal network. The code tries to retrieve stuff from googleapis.com and my work's dev environment doesn't allow that.

**Comment by cnishina** [comment] 2019-04-11 10:52
Closing as obsolete.

**Closed by cnishina** 2019-04-11 10:52 UTC
Labels: type: bug
