### ISSUE TITLE
--alternate_cdn has no effekt when downloading gecko driver

### ISSUE THREAD

**Issue by DuhSokola** [angular/webdriver-manager#294] opened 2018-01-04 09:09 UTC
It seems like the L29 overrides -alternate_cdn command line option

https://github.com/angular/webdriver-manager/blob/master/lib/binaries/gecko_driver.ts#L28
https://github.com/angular/webdriver-manager/blob/master/lib/binaries/gecko_driver.ts#L29

My usecase is to download geckodriver from internal server, not from github directly.
  
webdriver-manager update --alternate_cdn=XXXXXX

**Comment by elgohr** [comment] 2018-01-06 07:49
+1 but seems to be a duplicate of https://github.com/angular/webdriver-manager/issues/96

**Comment by cnishina** [comment] 2018-03-08 21:27
Agree that this is a duplicated closed issue. I plan to close it; however, I have some questions about this. Maybe we can find a feature here.

## Why this is difficult to solve based on cdn setup.

* If you are using an alternative cdn, you could just wget the version or curl to download?
* If you need to use the geckodriver path in Protractor for direct connect or a local driver start, you could pass the binary paths in the Protractor configuration / via command line.

Currently your cdn would have to match the xml for ChromeDriver or selenium server or json responses from GitHub. Webdriver-manager could then parse this file and you could then download the right file. This means your cdn would have to exactly mirror either the google storage or github. 

## Questions here:

Are you hoping to bypass the webdriver-manager to download from an alternative cdn? How will it get the correct path? How would you like it to work? Will you provide the xml file for ChromeDriver?

**Comment by cnishina** [comment] 2018-03-08 21:32
Tagging this issue: https://github.com/angular/webdriver-manager/issues/300

^^^ Maybe a neat solution that we need to implement?

**Comment by cnishina** [comment] 2018-03-08 21:33
Let's track it in the other issue. Closing.

**Closed by cnishina** 2018-03-08 21:33 UTC

**Comment by stieler-it** [comment] 2018-04-05 08:52
@cnishina Can you please verify if this is actually a duplicate of #96? It appears #96 has already been fixed in 2016 but we are also experiencing this problem now. Without further investigation it looks like variable names have been refactored and now do not match any more.
