### ISSUE TITLE
Document setting alternative driver version

### ISSUE THREAD

**Issue by darabos** [angular/webdriver-manager#98] opened 2016-09-19 15:35 UTC
Since https://github.com/angular/webdriver-manager/pull/41 the config file is loaded from within the module itself. So it is no longer a user configuration file. @cnishina mentions that to override a version now we should use, for example, `webdriver-manager update --versions.chrome=2.24`. That command works to install the requested version, but that version will not be picked up by Protractor. Protractor uses `webdriver-manager/built/lib/binaries/chrome_driver.js` which again takes the version from the config file.

As a workaround I can set the ChromeDriver executable name (including version) with `protractor.conf.js`'s `chromeDriver` property. Is there a better way?

Since different Chrome versions require different ChromeDriver versions, I think it is a common wish to set a specific ChromeDriver version. Could you please include instructions for this in `README.md`? Thanks!

**Comment by cnishina** [comment] 2016-09-21 09:18
You should use `--versions.chrome` or you could override the value in your protractor configuration file. The chromedriver experience that you are facing is probably related to Issue #93. The file name has changed slightly on OSX.

* If you are using a selenium address in your configuration file, the chromedriver should work.

* If you are using direct connect, you should run `webdriver-manager update` locally in your project. I like to do this in the package.json "scripts".

   ```
{
  "dependencies": {
    "protractor": "^4.0.8"
  },
  "scripts": {
    "pretest": "webdriver-manager update --versions.chrome=2.23"
    "test": "protractor protractor.conf.js"
  }
}
   ```

Hope that helps. Anyway, I agree that we could have better documentation.

**Comment by hsuh** [comment] 2016-09-21 12:04
sorry, how do I change the webdriver default chrome driver? 

I've got 3 different drivers downloaded 2.2, 2.3 and 2.4 but the default is set to 2.2 and I can't seem to be able to figure out how to switch the default driver. Help!

**Comment by ollisal** [comment] 2016-09-22 14:02
@cnishina yeah, you can get a specific Chromedriver version installed by using the --versions.chrome flag. But as @darabos said, Protractor still tries to find and launch the default version as specified by config.json when you run tests using directConnect: true.

The only way to make Protractor use a different version (without altering the npm-installed config.json) is to set the `chromeDriver` setting in the config. But that requires you to specify a full path to the binary, even accounting for platform differences. In essence, you need to have something like this in your Protractor config:

```
chromeDriver: '../node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.24' + (process.platform.indexOf('win') === 0 ? '.exe' : '')
```

(With the .. prefix dependent on where your Protractor config is situated in).

So I don't think this is simply a documentation issue. Shouldn't webdriver-manager abstract away exactly these kinds of details (where to download, filename, etc)?

Maybe it should be possible to specify the versions or a full path to a config file via environment variables? This way you wouldn't need to pass the version through all layers in Protractor or whatever is immediately calling webdriver-manager.

**Comment by obie** [comment] 2017-01-03 21:13
bump

**Comment by cnishina** [comment] 2017-01-11 10:05
@ollisal this has been fixed. `directConnect` uses the `selenium/update-config.json` file to find the last driver downloaded. The important thing to note is that it is the last one and not the latest file available.

**Comment by rossjohnson90** [comment] 2017-02-20 11:28
I'm having a similar issue - under the selenium file I only have chomedriver 2.26 I've updated the config.json to 2.26 and the config.json file under "built" to 2.26 but when I run webdriver-manager start I see
`11:22:43] I/start - java -Dwebdriver.chrome.driver=C:\Users\ross.johnson\AppData\Roaming\npm\node_modules\protractor\node_modules\webdriver-manager\selenium\chromedriver_2.27.exe -Dwe
bdriver.gecko.driver=C:\Users\ross.johnson\AppData\Roaming\npm\node_modules\protractor\node_modules\webdriver-manager\selenium\geckodriver-v0.14.0.exe -jar C:\Users\ross.johnson\AppDat
a\Roaming\npm\node_modules\protractor\node_modules\webdriver-manager\selenium\selenium-server-standalone-3.1.0.jar -port 4444` the file its point to for chromedriver 2.27 doesnt even exist so I find it strange its still trying to run 2.27 and that there is no error

**Comment by mwsessom** [comment] 2017-03-13 13:13
+1

**Comment by org4582** [comment] 2017-03-30 15:03
+1

**Comment by rkrisztian** [comment] 2017-04-04 09:55
Works for me in a project generated with Angular CLI 1.0.0 (Using Protractor 5.1.1), and the following npm script:

```
    "e2e": "ng e2e --webdriver-update false",
    "pree2e": "webdriver-manager update --versions.chrome=2.28"
```

**Comment by majinliang123** [comment] 2018-07-23 07:22
+1

**Comment by cnishina** [comment] 2018-07-23 17:31
The documentation exists. Please see: https://github.com/angular/webdriver-manager/blob/master/docs/versions.md

I probably should have closed this issue after I added the versions.md. I am going to close this with cb3b70f48db6945d17110f111c3c0e1d7a1c75bc. If you believe this is still an issue after reading the documentation, feel free to open a new issue.

**Closed by cnishina** 2018-07-23 17:31 UTC
Labels: type: docs

**Comment by snehalbhalerao15** [comment] 2019-08-05 06:03
After running Webdiver-manager update --versions.chrome=75.1.0,  getting below error

Error code:135
Error msg: Could not find update-config. Json.  Run webdriver-manager update to download

Please suggest on this..

**Comment by cnishina** [comment] 2019-08-05 17:59
That is as designed, 75.1.0 is not a fully qualified chromedriver version.  This documentation was moved to https://github.com/angular/webdriver-manager/blob/legacy/docs/versions.md and the list of chromedrivers that could be downloaded are chromedriver.storage.googleapis.com

You should find something that matches your major version of your Chrome browser version.

**Comment by dallasnicol** [comment] 2019-09-03 20:24
@cnishina - I'm referencing your documentation and @rkrisztian post above, using

```
    "e2e": "ng e2e --webdriver-update false",
    "pree2e": "webdriver-manager update --versions.chrome=76.0.3809.126"
```
But I am getting Error 135, "Could not find update-config.json. Run 'webdriver-manager update' to download binaries." even though it does seem to be downloading them:

> [15:21:45] I/update - chromedriver: file exists /Users/u0162908/code/adam/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_76.0.3809.126.zip
> [15:21:45] I/update - chromedriver: unzipping chromedriver_76.0.3809.126.zip
