### ISSUE TITLE
webdriver-manager 12.1.5/12.1.6

### ISSUE THREAD

**Issue by benjaminbatista** [angular/webdriver-manager#419] opened 2019-09-06 14:31 UTC
Hello,

I'm using protractor 5.4.2 on my angular app.

When I'm running my e2e tests, I have some issue with ChromeDriver: 
If I'm using webdriver-manager 12.1.6
```  E/launcher - session not created: This version of ChromeDriver only supports Chrome version 76 ``` 
If I'm using webdriver-manager 12.1.5
```  E/launcher - session not created: This version of ChromeDriver only supports Chrome version 75 ```

These tests are running on Linux 64 with Google Chrome 74.0.3729.169 and I don't want to update Chrome. Why webdriver-manager is downloading the 'latest' version of ChromeDriver instead of using the matching Chrome version?

Thank you

**Comment by TravkinAlex** [comment] 2019-09-07 11:18
I don't think webdriver-manager has any knowledge of the installed version of Chrome browser, and frankly it never crossed my mind whether it should - it's not listed as a feature at all. You'll just have to provide the specific version of chromedriver that you need explicitly.

**Comment by benjaminbatista** [comment] 2019-09-09 12:15
Oh ok, I thought it was possible for webdriver-manager to know which Chrome version is installed in purpose to install the proper Chrome Driver version

**Comment by cnishina** [comment] 2019-09-16 20:04
It should always download the latest version since the majority of set ups use the latest version of Chrome. If you need a specific version of you could download that version by specifying it on the command line with --versions.chrome. I think understanding the installed version of Chrome is beyond the scope of this. Preferably we should download Chromium instead in the future.

Closing this as not an issue with webdriver-manager but as intended functionality.

**Closed by cnishina** 2019-09-16 20:04 UTC
