### ISSUE TITLE
Syntax error when using version 10.2.9

### ISSUE THREAD

**Issue by ayelkawar2** [angular/webdriver-manager#170] opened 2016-12-02 00:23 UTC
After updating to the newest version, I get the following error on running 'webdriver-manager' command.

C:\Users\\(user)\AppData\Roaming\npm\node_modules\webdriver-manager\built\lib\cli\logger.js:66
info(...msgs) {
         ^^^
SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\\(user)\AppData\Roaming\npm\node_modules\we
bdriver-manager\built\lib\cli\index.js:8:10)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by bathos** [comment] 2016-12-02 05:41
[This commit](https://github.com/angular/webdriver-manager/commit/c16bf9053fc90e4b5e89ab867c514d0622ab0716#diff-354f30a63fb0907d4ad57269548329e3) changed the build target from ES5 to ES6, effectively dropping support for node 4. This was have recognized — it’s mentioned in the changelog ("with node 6 on LTS, we can update the tsconfig to es6") and the test config was changed to remove node 4. While I don’t see an explicit statement about what versions of Node are intended to be supported, the fact that up until that point it had been tested against 4 seems to imply that node 4 was supported, prior to 10.2.9.

I think it may be a mistake that this was a patch bump.

**Comment by wswebcreation** [comment] 2016-12-02 06:01
Is the versioning of `webdriver-manager` still correct? In my opinion this is a breaking change and not a fix, so shouldn't the version be bumped to at least 10.3.x, or even 11.x.x?
Our complete buildstreet, that currently still runs on Docker with Node 4.5, fails.

**Comment by axelssonHakan** [comment] 2016-12-02 08:25
We are experiencing the same
This is definitely a breaking change

**Comment by aszwaj** [comment] 2016-12-02 08:25
Same issue on my CI. I think that version 10.2.10 which roll back the node 4 removal would be quite helpful.

**Comment by szikszail** [comment] 2016-12-02 08:40
I agree, please create a release with roll back to node 4 support.

**Comment by wswebcreation** [comment] 2016-12-02 09:08
Temp fixes could be:

- use `npm shrinkwrap` to set the version of `webdriver-manager`
- or if that won't work, do the following 

for those who use node 4.5. This will first wait during the `npm install` if protractor is loaded, if so, then downgrade to `webdriver-manager@10.2.8`

create a file (webdriver.manager.fix.js) in your root and add this
`````
'use strict';

const child_process = require('child_process');

(function protractorLoaded(){
    try{
        const protractor = require.resolve('protractor');
        console.log('Downgrade webdriver-manager to 10.2.8');
        child_process.execSync('cd ./node_modules/protractor && npm install webdriver-manager@10.2.8');
    }
    catch(e) {
        console.log('protractor, try again after 500 miliseconds');
        setTimeout(protractorLoaded, 500)
    }
})();
`````

and add this in your package.json

`````
"scripts":{
    "postinstall": "node ./webdriver.manager.fix.js"
}
`````

**Comment by cnishina** [comment] 2016-12-02 09:10
I'll roll this back tomorrow. Sorry about that...

**Comment by cnishina** [comment] 2016-12-02 09:27
I think what I'll do is [unpublish](https://docs.npmjs.com/cli/unpublish) package 10.2.9. Simply deprecating the change in npm appears that it would still install 10.2.9. Rolling back the change to 10.2.8 and publishing it again to the latest 10.2.10 feels wrong.

So unpublishing will leave the latest hot fix as 10.2.8 and I'll publish these changes with 11.0.0. (Keeping with semantic versioning).

- [ ] unpublish from npm
- [ ] remove tag 10.2.9
- [ ] publish 11.0.0 with adequate changelog info on the breaking change.

**Comment by wswebcreation** [comment] 2016-12-02 09:32
@cnishina 
Sounds good

**Comment by cnishina** [comment] 2016-12-02 09:38
`npm view webdriver-manager`

```
  versions:
   [ '0.0.1',
     '0.0.2',
     '0.0.3',
     '0.0.4',
     '0.0.5',
     '0.0.6',
     '0.0.7',
     '0.0.8',
     '1.0.0',
     '1.0.1',
     '2.0.0',
     '3.0.0',
     '4.0.0',
     '5.0.0',
     '5.1.0',
     '5.2.0',
     '6.0.0',
     '6.0.2',
     '7.0.0',
     '7.0.1',
     '8.0.0',
     '9.0.0',
     '10.0.0',
     '10.0.1',
     '10.0.2',
     '10.0.3',
     '10.0.4',
     '10.1.0',
     '10.2.0',
     '10.2.1',
     '10.2.2',
     '10.2.3',
     '10.2.4',
     '10.2.5',
     '10.2.6',
     '10.2.7',
     '10.2.8',
     '11.0.0-beta.0' ],
```

**Comment by wswebcreation** [comment] 2016-12-02 09:41
Very nice and very quick!!

**Comment by cnishina** [comment] 2016-12-02 09:48
Huzzah. Done! 

Sorry about that everyone...I end up switching node versions with [nvm](https://github.com/creationix/nvm) so often that I forget that upgrading node is a breaking change.

**Comment by wswebcreation** [comment] 2016-12-02 09:50
@cnishina 

Shit happens ;-). Again tnx for fixing this very fast!

**Comment by wswebcreation** [comment] 2016-12-02 09:59
@cnishina 

I'm still seeing 10.2.9 in the version list
`npm view webdriver-manager`

`````
 versions:
   [ '0.0.1',
     '0.0.2',
     '0.0.3',
     '0.0.4',
     '0.0.5',
     '0.0.6',
     '0.0.7',
     '0.0.8',
     '1.0.0',
     '1.0.1',
     '2.0.0',
     '3.0.0',
     '4.0.0',
     '5.0.0',
     '5.1.0',
     '5.2.0',
     '6.0.0',
     '6.0.2',
     '7.0.0',
     '7.0.1',
     '8.0.0',
     '9.0.0',
     '10.0.0',
     '10.0.1',
     '10.0.2',
     '10.0.3',
     '10.0.4',
     '10.1.0',
     '10.2.0',
     '10.2.1',
     '10.2.2',
     '10.2.3',
     '10.2.4',
     '10.2.5',
     '10.2.6',
     '10.2.7',
     '10.2.8',
     '10.2.9',
     '11.0.0-beta.0' ]
`````

**Comment by cnishina** [comment] 2016-12-02 10:05
Leaving this open so people encountering the same issue will see it.

**Comment by cnishina** [comment] 2016-12-02 10:08
Hello! Webdriver-manager 10.2.9 was published earlier today and it was causing problems because it requires node 6. To resolve this problem, I unpublished 10.2.9. What this means is that you'll just need to remove the node_module for webdriver-manager and do a fresh `npm install`.

Version 11.0.0 was published after that with notes on breaking change for node 6.

**Comment by cnishina** [comment] 2016-12-02 10:10
Will close this issue next week.

**Comment by wswebcreation** [comment] 2016-12-02 10:11
But 10.2.9 is still in NPM, I thought you removed it

**Comment by cnishina** [comment] 2016-12-02 10:24
10.2.9 has been removed.

```
npm i -g webdriver-manager@~10.2.7
/Users/cnishina/.nvm/versions/node/v6.9.1/bin/webdriver-manager -> /Users/cnishina/.nvm/versions/node/v6.9.1/lib/node_modules/webdriver-manager/bin/webdriver-manager
/Users/cnishina/.nvm/versions/node/v6.9.1/lib
└── webdriver-manager@10.2.8
```

**Comment by cnishina** [comment] 2016-12-02 10:26
Also, created a [stackoverflow](http://stackoverflow.com/questions/40929821/syntax-error-on-webdriver-manager-10-2-9/40929822#40929821) that references this issue.

**Comment by cnishina** [comment] 2016-12-02 10:27
@wswebcreation is it possibly cached? You could potentially delete the cached version `~/.npm/webdriver-manager/10.2.9`.

**Comment by wswebcreation** [comment] 2016-12-02 10:28
It was not cached, the log I pasted was from the npm command, before is wasn't showing. I'll do a fresh install now on my local machine (new install of project en modules). If you hear nothing it's fixed ;-)

**Comment by cnishina** [comment] 2016-12-02 10:29
Alright, well I'm headed to bed so fingers crossed!

**Comment by wswebcreation** [comment] 2016-12-02 10:29
Good night!

**Comment by huerlisi** [comment] 2016-12-02 15:14
Thanks for the quick fix. There's some issues for people using caching layers like Artifactory though. It's not so simple to delete releases there and it might even be prohibited by legal requirements (Entreprise problems;-).

So when using a proper semantic versioned dependency like `^10.2.8` it will keep failing when using an older node version. Specifying a specific version (10.2.8) would work, but might not be want people want. 

And it's even trickier: packages like `protractor` are using such a semantic version, so it's impossible to ensure 10.2.9 won't be used (without using shrinkwrap).

So I propose to re-release a version 10.2.10, reverting the change, including an updated changelog.

**Comment by cnishina** [comment] 2016-12-02 17:43
@huerlisi I did think about Artifactory last night and was hoping no one had that problem. I'll cut a release for 10.2.8 to be 10.2.10 and update the changelog.

**Comment by cnishina** [comment] 2016-12-02 19:24
Quick update. 10.2.10 has been released to resolve caching layers like Artifactory w/ an updated changelog. Thanks @huerlisi.

**Comment by tomreece** [comment] 2016-12-02 20:44
Node/npm noob here, why would anyone ever pull down a version of something instead of releasing a new version that fixes the issue? Do you force push to your git branches too?

**Comment by cnishina** [comment] 2016-12-02 21:08
@tomreece It was late last night and made a decision. That decision although was not probably the right decision, I later released a new version with the reverted change.

In regards to your comment about force pushing changes, the master branch does not allow force pushing so I just added another commit with some updates on the changelog. I hope that helps.

**Comment by huerlisi** [comment] 2016-12-02 21:44
@cnishina your fast response is very much appreciated!

**Comment by cnishina** [comment] 2016-12-08 20:29
It's been a week. Closing this issue!

**Closed by cnishina** 2016-12-08 20:29 UTC
Labels: status: resolved!, type: bug

**Comment by twolfson** [comment] 2017-01-07 08:19
This is still broken for Node.js@4.x.x. I don't understand why support for 4.x.x was dropped when it's still in active LTS until 2017-04-01 (3 months left) and being maintained until 2018-04-01 (15 months left) =/

https://github.com/nodejs/LTS/tree/772147f5d1493a13851084dd8f262352c64e5fbd

**Comment by KakadeVrushali** [comment] 2017-01-19 06:59
I am still facing this issue. 
webdriver-manager version is 11.1.1
node version is 6.5.0

Please suggest the solution

**Comment by wswebcreation** [comment] 2017-01-19 07:01
@KakadeVrushali 

Have you tried updating to node > 7 with NVM?

**Comment by KakadeVrushali** [comment] 2017-01-19 08:16
Yes I have also tried with node v7.4.0 but faced same problem

**Comment by wswebcreation** [comment] 2017-01-19 12:17
@KakadeVrushali 

![image](https://cloud.githubusercontent.com/assets/11979740/22106565/88ba0e1c-de49-11e6-9e61-35e50f84e2dd.png)

![image](https://cloud.githubusercontent.com/assets/11979740/22106574/a05eb892-de49-11e6-8673-dd3e4063791a.png)

This is my setup and I don't have the problem.

**Comment by jamshid** [comment] 2017-01-20 20:19
Are you really saying the *current* version of node and npm in ubuntu:16.04 (and even 16.10!) is too old to support?

Really seems like you should either get Ubuntu repos updated to a more recent nodejs, or support the "current" node on LTS releases.

Example Dockerfile reproducing the failure:
```
FROM	ubuntu:16.10
RUN	apt-get update
RUN apt-get install -y nodejs npm
RUN npm install -g bower grunt-cli protractor protractor-html-screenshot-reporter
RUN ln -s /usr/bin/nodejs /usr/bin/node
RUN webdriver-manager update
```

```
...
Step 6/6 : RUN webdriver-manager update
/usr/local/lib/node_modules/protractor/node_modules/webdriver-manager/built/lib/cli/logger.js:66
     info(...msgs) {
            ^^^
```

Or I guess I should be running https://deb.nodesource.com/setup to install node instead of using apt-get?

**Comment by caneraydinbey** [comment] 2017-01-23 13:53
vegan@vegan:~$ nodejs -v
v5.12.0
vegan@vegan:~$ npm -v
3.8.6

but still working.

**Comment by cnishina** [comment] 2017-01-24 09:54
@caneraydinbey Not sure what the context of the comment above is about. Looks like you are installing a really old version of protractor. You should try to stay current.

**Comment by cnishina** [comment] 2017-01-24 09:56
Also, I'm planning to lock this conversation since it has been resolved. Please open up a new issues. Closed issues do not get a lot of attention.
