### ISSUE TITLE
webdriver-manager is trying to connect to some site in a sneky way. Why?

### ISSUE THREAD

**Issue by attila123** [angular/webdriver-manager#211] opened 2017-02-20 09:33 UTC
I started webdriver-manager with
nohup webdriver-manager start --seleniumPort $SELENIUM_PORT >.ci/webdriver-manager_start.log 2>&1 &

(SELENIUM_PORT being 4444). In the log all I see it fails to start because it tries to connect to some random server???
What is going on?

webdriver-manager: using global installed version 12.0.2
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 172.217.18.208:443
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)

**Comment by J0nesP** [comment] 2017-02-21 10:57
## OS:
Windows 7 (64 bit)

## Versions:
Node: 6.9.5
Npm: 4.2.0
webdriver-manager global installed version 12.0.2

## Reproduce steps:
I have the same Issue...
Since I have updated my webdriver-manager (uninstall and installing the new one), I get the same error. Here is what I did:


1) npm uninstall webdriver-manager -g ==> OK, webdriver was uninstalled
2) npm install -g webdriver-manager ==> OK, webdriver was installed (No warnings or errors!)
3) webdriver-manager update ==> Error 1 in the Screenshot
4) webdriver-manager status ==> OK, No Drivers Present
5) webdriver-manager update --standalone ==> Error 2 in the Screenshot
6) webdriver-manager --ignore_ssl --proxy=http://127.0.0.1:3128 update ==> Error 3 in the Screenshot

### This are all commands I used before and they were working.

![image](https://cloud.githubusercontent.com/assets/22075128/23161373/311b60ca-f82a-11e6-9766-5b5aeec32de6.png)

I even updated the Drivers manually, but then i still get the same error as attila123. Why does he try to connect to a randomserver??

![image](https://cloud.githubusercontent.com/assets/22075128/23161834/e3135804-f82b-11e6-8157-7583eeda684a.png)

**I don't understand this Problem. Can you please help me?**

## Current workaround:
None

**Comment by michaelblumenstein** [comment] 2017-02-22 14:15
This issue is already discussed by #207 and an according pull request is currently active.

The problem you have is that neither --ignore_ssl nor --proxy is actually used to resolve the files.

**Comment by cnishina** [comment] 2017-02-23 23:04
So what is probably happening is that 172.217.21.208 is probably making this call: `https://selenium-release.storage.googleapis.com/`. I do agree that this has sort of already been discussed by #207 and the proxy flag is not being passed down.

I do have a fix in flight however I have not addressed the comments yet. For now, you could downgrade to webdriver-manager 11.0.0. If you are using Protractor@latest, this should work if you are using `seleniumAddress` in your configuration. However, downgrading will not work if you plan to use a local driver provider or direct connect.

I'll close this bug as well with #207 when my fix is merged and released.

**Comment by cnishina** [comment] 2017-02-23 23:11
Also, to address the "sneaky things" webdriver-manager is doing...this is what's happening.

For IEDriver, selenium-standalone-server, and chromedriver:

- For the google storage site, it grabs the xml, parses it and looks for the latest available for your os type and arch.
- After it grabs the xml, it saves it as a cache in your output directory (default is `selenium/`)
- Then downloads the latest driver / jar file

For Geckodriver:

- For github, it grabs the json file, parses it, and looks for the latest available gecko driver for your os type and arch.
- After it grabs the json, it saves it as a cache in your output directory (default is `selenium/`)
- Then downloads the latest driver

Finally:

- Writes an `update-config.json` file in your output directory. This will have all the drivers downloaded and also the value that is the latest
- When you use Protractor with local driver provider or direct connect, it reads this file and uses the last downloaded file to launch the browser directly or launch the browser via the standalone server

**Comment by cnishina** [comment] 2017-03-06 19:50
Closing this issue with #207

**Closed by cnishina** 2017-03-06 19:50 UTC
Labels: type: bug

**Comment by attila123** [comment] 2017-03-08 11:14
Hi @cnishina,
Thanks for your support!
I have a question about this bug. The problem is that when I run this "webdriver-manager start" command with 12.0.2 it detects from the net that e.g. there is a new selenium server (e.g. now it suddenly wants to use selenium-server-standalone-3.3.0.jar instead of 3.2.0):

webdriver-manager: using global installed version 12.0.2
[11:51:14] I/start - java -Djava.security.egd=file:///dev/./urandom -Dwebdriver.gecko.driver=/home/jenkins/.nvm/versions/node/v6.9.5/lib/node_modules/webdriver-manager/selenium/geckodriver-v0.14.0 -Dwebdriver.chrome.driver=/home/jenkins/.nvm/versions/node/v6.9.5/lib/node_modules/webdriver-manager/selenium/chromedriver_2.27 -jar /home/jenkins/.nvm/versions/node/v6.9.5/lib/node_modules/webdriver-manager/selenium/selenium-server-standalone-3.3.0.jar -port 7840
[11:51:14] I/start - seleniumProcess.pid: 6236
Error: Unable to access jarfile /home/jenkins/.nvm/versions/node/v6.9.5/lib/node_modules/webdriver-manager/selenium/selenium-server-standalone-3.3.0.jar
[11:51:14] I/start - Selenium Standalone has exited with code 1

The problem with this that whenever there is a new version of e.g. selenium server, our build breaks.
I would expect "webdriver-manager start" to work totally offline and use the selenium and chrome driver which is currently installed, and do not try to update them. Is this possible to achieve?
I see that #207 is closed now, but there is no newer version of webdriver-manager than 12.0.2.
I am not sure that downgrading webdriver-manager to 11.1.1 would help, because the latest protractor 5.1.1 also uses webdriver-manager 12.0.2:

└─┬ protractor@5.1.1 
  ├── @types/node@6.0.64 
  ├── @types/selenium-webdriver@2.53.42 
  ├─┬ selenium-webdriver@3.0.1
  │ └── rimraf@2.6.1 
  └─┬ webdriver-manager@12.0.2
    └─┬ request@2.80.0 
      ├── caseless@0.12.0 
      ├─┬ har-validator@4.2.1 
      │ ├─┬ ajv@4.11.4 
      │ │ ├── co@4.6.0 
      │ │ └─┬ json-stable-stringify@1.0.1 
      │ │   └── jsonify@0.0.0 
      │ └── har-schema@1.0.5 
      ├─┬ http-signature@1.1.1
      │ └── sshpk@1.11.0 
      ├── performance-now@0.2.0 
      └── qs@6.3.2

**Comment by attila123** [comment] 2017-03-09 11:42
So my main problem is that 'webdriver-manager start' is trying to update selenium and drivers, and that is really bad, because I just want it to start, not to update stuff. For example now I was forced to update the chome driver to 2.28 because of this, which triggered a forced chrome update to 55+. All of these before a deadline. :(
Please, please create a new release for webdriver-manager to release the fix for this problem!

**Comment by cnishina** [comment] 2017-03-09 18:08
This is all documented how webdriver-manager works.  If you don't want to use the latest version, you can just pin the version with `webdriver-manager update --versions.chrome=2.26` and `webdriver-manager start --versions.chrome=2.26`. My suggestion for your problem: if you do not like the current mechanics, you could just use an older version. Please refer to the changelog to see which version works best for you.

The change we made to webdriver-manager is that it will grab the latest on `update`. It also checks for the latest on `start`. During the `start` method it validates the cache, and downloads a new list if it is stale. It does not download new binaries. If you do not have the latest, `start` does not work. This forces the user to make a decision: should I pin a version or run `update` again to get the latest version.

Hope that helps. If you still think it can be better, feel free to put in a PR and I'll happily take a look at it.

**Comment by cnishina** [comment] 2017-03-09 18:35
Also, I just did a new release with the proxy and ignore ssl change. It is published to npm so hopefully this works for you. Good luck with your deadline.

**Comment by attila123** [comment] 2017-03-09 23:59
@cnishina thx for the information, did not know that. I would totally decouple 'start' from this cache validation / list download magic. Remember what Uncle Bob said? One function does one thing. Similarly, I don't understand why 'start' has to have these side effects. Wouldn't it be better to add some other command, like 'update-list' (or whatever name is more appropriate).
But anyway I will take into use these extra arguments to pin the versions.
Thx also for the new release!

**Comment by attila123** [comment] 2017-03-10 09:03
I created a PR #220 explaining my use cases.
